/home/eljah/apps/buscrawl/logs/client.log
/home/eljah/apps/buscrawl/logs/stream.log
/home/eljah/apps/buscrawl/logs/dashboard.log
/home/eljah/apps/buscrawl/logs/dashboard-cache.log
/home/eljah/apps/buscrawl/logs/trace-cache.log
{
    size 1G
    rotate 5
    missingok
    notifempty
    copytruncate
    compress
    delaycompress
    su root root
}
